version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - restore_cache:
          name: Restore go modules cache
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Download go modules to cache
          command: go mod download
      - save_cache:
          name: Save go modules cache
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod/cache
      - run:
          name: Unit Test
          command: |
            go test -v ./...
      - run:
          name: Acceptance Test
          command: |
            TF_ACC=1 go test -v ./...
workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
